import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[5,8,7],[3,4,9,],[2,1,6]])
arr3 = np.array([12,45,87])
arr4 = np.array(10)
# print(arr1.shape)
# print(arr2.shape)
print('>>>>>>>>>>>>.Addition.>>>>>>>>>>>>>')
print(np.add(arr1,arr2))
print('>>>>>>>>>>>>.Subtraction.>>>>>>>>>>')
print(np.subtract(arr1,arr3))
print('>>>>>>>>>>>Multiply>>>>>>>>>.')
print(np.multiply(arr1,arr4))
print('>>>>>>>>>>>>.Divide>>>>>>>>>')
print(np.divide(arr1,arr2))
print('<<<<<<<<<<<<Exponent>>>>>>>>>>>>.')
print(np.power(arr1,arr2))
print('>>>>>>>>>>>>>Modulus>>>>>>>>>>>')
print(np.mod(arr3,arr4))
print('>>>>>>>>..>>>>>>>Reciprocal>>>>>>>.')
print(np.reciprocal(arr1,arr2))

# print(arr1+arr3)
# print(arr1-arr2)
# print(arr1*arr4)
# print(arr3/arr4)
# print(arr3//arr4)
# print(arr2%arr4)