import numpy as np
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.concatenate((arr1,arr2),axis=0)
print("ColumnWise Concatenation")
print(arr3)
arr4 = np.concatenate((arr1,arr2),axis=1)
print("RowWise Concatenation")
print(arr4)
arr5 = np.stack((arr1,arr2),axis=0)
print("ColumnWise Stack")
print(arr5)
arr6 = np.stack((arr1,arr2),axis=1)
print("RowWise Stack")
print(arr6)
arr7 = np.hstack((arr1,arr2))
print("H Stack Or RowWise Concatenation")
print(arr7)
arr8 = np.vstack((arr1,arr2))
print("V Stack or ColumnWise Concatenation")
print(arr8)
arr9 = np.dstack((arr1,arr2))
print("D Stack or Depth Stack")#Transform the column into rows and vice verss of two different arrays
print(arr9)
